version: '3.1'

services:

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  elastic:
    image: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
